### PR TITLE
feat: impl `Post` module

### PR DESCRIPTION
**Pull request by Michael-Liendo**

### CODE REVIEW

**Review by EstebanBorai — COMMENTED** [review]
@Michael-Liendo looking good! I thunk next step would be providing the Service!

**Comment by Michael-Liendo** [comment]
Already @EstebanBorai!

**Comment by EstebanBorai** [comment]
> Already @EstebanBorai! I make the service

Nice!

**Review by EstebanBorai — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
